name: Build Go Executable

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch

jobs:
  build:
    name: Build Go Executable
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21" # Replace with your desired Go version

      # Step 3: Build the executable
      - name: Build the executable
        run: |
          mkdir -p builds
          GOOS=windows GOARCH=amd64 go build -o builds/verdictsniffer.exe .
